Update MyFirebaseMessagingService.java
to rectify this error

MyFirebaseMessagingService.java:109: error: package
        Notification does not exist
        .setStyle(new Notification.BigPictureStyle().bigPicture(bitmap_image))